FROM node:25-alpine AS builder

# Environment variables used for building and Sentry release
ARG SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT

ARG GITHUB_SHA
ARG GITHUB_REF

ENV NODE_OPTIONS="--max-old-space-size=4096"

# Install all dependencies, including dev, and build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build