# Convert old environment variables to new ones
export NUXT_PUBLIC_SENTRY_CONFIG_ENVIRONMENT=${DEPLOYMENT_ENV}

export NUXT_PUBLIC_DEPLOYMENT_ENV=${DEPLOYMENT_ENV}
export NUXT_PUBLIC_DEMO_MODE=${DEMO_MODE}

export NUXT_PUBLIC_API_HOST=${API_HOST}
export NUXT_PUBLIC_API_PROTOCOL=${API_PROTOCOL}

export NUXT_PUBLIC_MANAGE_ACCOUNT_URL=${MANAGE_ACCOUNT_URL}

export NUXT_PUBLIC_OKTA_ISSUER=${OAUTH_ISSUER}
export NUXT_PUBLIC_OKTA_CLIENT_ID=${APP_CLIENT_ID}

node .output/server/index.mjs